PaySharp.Web/ViewModels/ClientViewModel.cs
using Microsoft.AspNetCore.Mvc;
using PaySharp.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PaySharp.Web.ViewModels
{
    public class ClientViewModel
    {
        [Key]
        public long Id { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(35)]
        public string Name { get; set; }
                
        public ICollection<AccountViewModel> Accounts { get; set; }

        public ICollection<UserViewModel> Users { get; set; }
    }
}

PaySharp.Web/Areas/Administration/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using PaySharp.Services.Contracts;
using PaySharp.Services.DTO;
using PaySharp.Services.Exceptions;
using PaySharp.Web.Areas.Administration.ViewModels;
using PaySharp.Web.Mappers;
using PaySharp.Web.Utilities;
using PaySharp.Web.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PaySharp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [CustomAuthorize("Admin")]
    public class ClientController : Controller
    {
        private readonly IClientService clientService;
        private readonly IViewModelMapper<ClientDTO, ClientViewModel> clientMapper;
        private readonly IViewModelMapper<AccountDTO, AccountViewModel> accountMapper;
        private readonly IViewModelMapper<UserDTO, UserViewModel> userMapper;

        public ClientController(IClientService clientService,
            IViewModelMapper<ClientDTO, ClientViewModel> clientMapper,
            IViewModelMapper<AccountDTO, AccountViewModel> accountMapper,
            IViewModelMapper<UserDTO, UserViewModel> userMapper)

        {
            this.clientService = clientService ?? throw new ArgumentNullException(nameof(clientService));
            this.clientMapper = clientMapper ?? throw new ArgumentNullException(nameof(clientMapper));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
            this.userMapper = userMapper ?? throw new ArgumentNullException(nameof(userMapper));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateClient(ClientViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {

                    return RedirectToAction("Index", "Dashboard", new { area = "Administration" });
                }

                var client = await clientService.CreateClientAsync(model.Name);

                return Ok($"Client with name {model.Name} was added successfully");
            }
            catch (EntityAlreadyExistsException ex)
            {
                return BadRequest(ex.Message);
            }


        }
        [HttpGet]
        public async Task<IActionResult> ClientDetails(long id)
        {
            var client = await clientService.GetClientAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            var vm = new ClientViewModel()
            {
                Id = client.ClientId,
                Name = client.Name,
                Accounts = client.Accounts.Select(a => accountMapper.MapFrom(a)).ToList(),
                Users = client.UsersClients.Select(uc => userMapper.MapFrom(uc.User)).ToList()
            };
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> ShowAllClients(int? currentPage)
        {
            var clients = await clientService.TakeNumberOfClientsAsync(currentPage ?? 1);
            var allClients = clients.Select(c => clientMapper.MapFrom(c));
            var count = await clientService.GetAllClientsCountAsync();

            var vm = new PaginationClientViewModel()
            {
                CurrentPage = currentPage ?? 1,
                NextPage = (currentPage ?? 1) + 1,
                PrevPage = (currentPage ?? 1) - 1,
                Count = count,
                Clients = allClients
            };

            return PartialView("Clients/_ShowClientsPartial", vm);
        }

        [HttpGet]
        public async Task<IActionResult> GetClientUsers(long id)
        {
            var client = await clientService.GetClientAsync(id);
            var vm = new ClientViewModel()
            {
                Users = client.UsersClients.Select(uc => userMapper.MapFrom(uc.User)).ToList()
            };
            return PartialView("Users/_ShowClientUsersPartial", vm.Users);
        }

        [HttpPost]
        public async Task<IActionResult> GetClient(string searchName)
        {
            try
            {
                var client = await clientService.GetClientAsync(searchName);
                var vm = new ClientViewModel()
                {
                    Id = client.ClientId,
                    Name = client.Name,
                    Accounts = client.Accounts.Select(a => accountMapper.MapFrom(a)).ToList(),
                    Users = client.UsersClients.Select(uc => userMapper.MapFrom(uc.User)).ToList()
                };

                return View("../Client/ClientDetails", vm);
            }
            catch (EntityNotFoundException ex)
            {

                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public async Task<JsonResult> FindClientbyName(string prefix)
        {

            if (string.IsNullOrEmpty(prefix))
            {
                return Json(string.Empty);
            }

            var allClientsContaining = await clientService.FindClientContainingAsync(prefix);

            return Json(allClientsContaining);
        }
    }
}

PaySharp.Web/Areas/Administration/Views/Shared/Clients/_NewClientPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model PaySharp.Web.ViewModels.ClientViewModel

    <div class="card">

        <div class="card-body">
            <h4 id="rw-fl-fvlength">Create Client</h4>

            <form id="create-client-form" asp-controller="Client" asp-action="CreateClient" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                

                <div class="form-group margin-top-20 margin-bottom-0">
                    <button class="btn btn-light" type="submit">Submit</button>
                </div>
            </form>

        </div>
    </div>
   

PaySharp.Web/Areas/Administration/Views/Shared/Clients/_ShowClientsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PaySharp.Web.Areas.Administration.ViewModels.PaginationClientViewModel

<div class="card margin-bottom-0">
    <div class="card-body">
        <h4>Clients</h4>
     
        <div class="table-responsive">
            <table id="table-all-clients" class="table margin-bottom-0">
                <thead>
                    <tr>

                        <th width="200" scope="col">Name</th>

                    </tr>
                </thead>
                @foreach (var client in Model.Clients)
                {


                    <tbody>

                        <tr>

                            <td>
                                <div class="user user--rounded user--bordered">
                                    <div class="user__name">
                                        <strong>@client.Name</strong>

                                    </div>
                                </div>
                            </td>
                            <td>
                                <form class="create-account-client-test" asp-area="Administration" asp-controller="Account" asp-action="Create" method="post">
                                    <input type="hidden" name="id" value="@client.Id" />
                                    <input type="submit" class="btn btn-light btn-sm" name="upvote" value="Create Account" />
                                </form>
                            </td>
                            <td>
                                <form asp-area="Administration" asp-controller="Client" asp-action="ClientDetails" asp-route-id="@client.Id" method="get">
                                    <input type="submit" class="btn btn-light btn-sm" value="Details">
                                </form>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
            <div>
                <ul class="pagination">
                    @if (Model.PrevPage < 1)
                    {
                        <li class="page-item disabled">
                            <div data-currentpage="@Model.PrevPage">
                                <a class="page-link">Prev</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="page-item ">
                            <div data-currentpage="@Model.PrevPage">
                                <a id="paging-clients-prev" asp-area="Administration" asp-controller="Client"
                                   asp-action="ShowAllClients"
                                   asp-route-currentpage="@Model.PrevPage "
                                   class="page-link">Prev</a>
                            </div>
                        </li>
                    }

                    <li class="page-item active">
                        <div id="paging-transaction-current">
                            <a class="page-link">@Model.CurrentPage</a>
                        </div>
                    </li>
                    @if (Model.CurrentPage < Model.TotalPages)
                    {

                        <li class="page-item">
                            <div data-currentpage="@Model.TotalPages">
                                <a id="paging-clients-last" asp-area="Administration" asp-controller="Client"
                                   asp-action="ShowAllClients"
                                   asp-route-currentpage="@Model.TotalPages"
                                   class="page-link" disabled>Last:@Model.TotalPages</a>

                            </div>
                        </li>
                    }
                    @if (Model.NextPage > Model.TotalPages)
                    {
                        <li class="page-item disabled">
                            <div class="" data-currentpage="@Model.NextPage">
                                <a class="page-link">Next</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="page-item ">
                            <div data-currentpage="@Model.NextPage">
                                <a id="paging-clients-next" asp-area="Administration" asp-controller="Client"
                                   asp-action="ShowAllClients" asp-route-currentpage="@Model.NextPage"
                                   class="page-link">Next</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
        

<div class="card">
    <div class="card-body">
        <h4 id="rw-fig-btn">Client Search</h4>
        <form asp-controller="Client" asp-action="GetClient" method="post">
            <div class="row">
                <div class="">
                    <div class="input-group">
                        <span class="input-group-prepend">
                            <button class="btn btn-light" type="submit">Go!</button>
                        </span>
                        <input type="text" id="search-client-auto" name="searchName" size="35" class="form-control" placeholder="Search for client.." >
                        <span id="message-autocomplete" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>

<div class="modal fade" id="formExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <span id="target-modal-account">

                    @await Html.PartialAsync("Accounts/_CreateAccountPartial", new AccountViewModel())
                </span>


            </div>

        </div>
    </div>
</div>

PaySharp.Web/Areas/Administration/Views/Shared/Clients/_UserClientsPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<PaySharp.Web.ViewModels.ClientViewModel>

<div class="card margin-bottom-0">
    <div class="card-body">
        <h4>Clients</h4>
        <p class="subtitle margin-bottom-20">All user clients</p>
        @if (Model.Count() == 0)
        {
            <p>No clients</p>
        }
        else
        {

            <div class="table-responsive">
                <table id="table-all-clients" class="table margin-bottom-0">
                    <thead>
                        <tr>

                            <th width="200" scope="col">Name</th>

                        </tr>
                    </thead>
                    @foreach (var client in Model)
                    {


                        <tbody>

                            <tr>

                                <td>
                                    <div class="user user--rounded user--bordered">
                                        <div class="user__name">
                                            <strong>@client.Name</strong>

                                        </div>
                                    </div>
                                </td>
                                
                                <td>
                                    <form asp-area="Administration" asp-controller="Client" asp-action="ClientDetails" asp-route-id="@client.Id" method="get">
                                        <input type="submit" class="btn btn-light btn-sm" value="Details">
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    }
                </table>
            </div>
        }
    </div>
</div>