PaySharp.Web/ViewModels/TransactionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PaySharp.Web.ViewModels
{
    public class TransactionViewModel
    {
        public long Id { get; set; }

        public long SenderAccountID { get; set; }

        public AccountViewModel SenderAccount { get; set; }

        public long ReceiverAccountID { get; set; }

        public AccountViewModel ReceiverAccount { get; set; }

        public string Description { get; set; }

        public decimal Amount { get; set; }

        public DateTime TimeStamp { get; set; }

        public string Status { get; set; }

        public bool IsSend { get; set; }

        public bool IsRecieved { get; set; }

        // public List<SelectListItem> Accounts { get; set; }
        public IEnumerable<AccountViewModel> Accounts { get; set; }

    }
}

PaySharp.Web/Areas/User/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PaySharp.Services.Contracts;
using PaySharp.Services.DTO;
using PaySharp.Web.Mappers;
using PaySharp.Web.Utilities;
using PaySharp.Web.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PaySharp.Web.Areas.User.Controllers
{
    [Area("User")]
    [CustomAuthorize("User")]
    public class TransactionController : Controller
    {
        private readonly ITransactionService transactionService;
        private readonly IAccountService accountService;
        private readonly IAuthorizationManager authorizationManager;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly IViewModelMapper<TransactionDTO, TransactionViewModel> transactionMapper;
        private readonly IViewModelMapper<AccountDTO, AccountViewModel> accountMapper;

        public TransactionController(ITransactionService transactionService,
            IAccountService accountService,
            IAuthorizationManager authorizationManager,
            IHttpContextAccessor contextAccessor,
            IViewModelMapper<TransactionDTO, TransactionViewModel> transactionMapper,
            IViewModelMapper<AccountDTO, AccountViewModel> accountMapper)
        {
            this.transactionService = transactionService ?? throw new ArgumentNullException(nameof(transactionService));
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.authorizationManager = authorizationManager ?? throw new ArgumentNullException(nameof(authorizationManager));
            this.contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
            this.transactionMapper = transactionMapper ?? throw new ArgumentNullException(nameof(transactionMapper));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
        }


        [HttpGet]
        public async Task<IActionResult> List(int? currentPage, long? accountId)
        {
            var token = contextAccessor.HttpContext.Request.Cookies["SecurityToken"];
            var currentUserId = authorizationManager.GetLoggedUserId(token);
            var userAccounts = await accountService.GetUserAccountsAsync(currentUserId);
            var accountsViewModels = userAccounts.Select(a => accountMapper.MapFrom(a));
            if (accountId == null)
            {
                var allUserTransactions = await transactionService.GetAllUserTransactions(currentUserId, currentPage ?? 1);
                var transactionsViewModel = allUserTransactions.Select(t => transactionMapper.MapFrom(t));
                var count = await transactionService.GetTransactionsCount(currentUserId, null);
                var vm = new PaginationTransactionsViewModel()
                {
                    CurrentPage = currentPage ?? 1,
                    NextPage = (currentPage ?? 1) + 1,
                    PrevPage = (currentPage ?? 1) - 1,
                    Count = count,
                    Data = transactionsViewModel,
                    UserAccounts = accountsViewModels,

                };

                return View(vm);
            }
            else
            {
                var accountTransactions = await transactionService
                    .GetUserTransactionsByAccount(accountId ?? 1, currentUserId, currentPage ?? 1);
                var transactionsViewModel = accountTransactions.Select(t => transactionMapper.MapFrom(t));
                var accountPreSelected = await accountService.GetAccountAsync((long)accountId);
                var accountViewModel = accountMapper.MapFrom(accountPreSelected);
                var count = await transactionService.GetTransactionsCount(currentUserId, accountId);
                var vm = new PaginationTransactionsViewModel()
                {
                    CurrentPage = currentPage ?? 1,
                    NextPage = (currentPage ?? 1) + 1,
                    PrevPage = (currentPage ?? 1) - 1,
                    Count = count,
                    Data = transactionsViewModel,
                    UserAccounts = accountsViewModels,
                    PreSelectedAccount = accountViewModel
                };

                return View(vm);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetTransactions(int? currentPage, long? accountId)
        {
            var token = contextAccessor.HttpContext.Request.Cookies["SecurityToken"];
            var currentUserId = authorizationManager.GetLoggedUserId(token);
            var userAccounts = await accountService.GetUserAccountsAsync(currentUserId);
            var accountsViewModels = userAccounts.Select(a => accountMapper.MapFrom(a));
            if (accountId == null)
            {
                var allUserTransactions = await transactionService.GetAllUserTransactions(currentUserId, currentPage ?? 1);
                var transactionsViewModel = allUserTransactions.Select(t => transactionMapper.MapFrom(t));
                var count = await transactionService.GetTransactionsCount(currentUserId, null);
                var vm = new PaginationTransactionsViewModel()
                {
                    CurrentPage = currentPage ?? 1,
                    NextPage = (currentPage ?? 1) + 1,
                    PrevPage = (currentPage ?? 1) - 1,
                    Count = count,
                    Data = transactionsViewModel,
                    UserAccounts = accountsViewModels,

                };

                return PartialView("Transactions/_AllUserTransactionsPartial", vm);
            }
            else
            {
                var accountTransactions = await transactionService
                    .GetUserTransactionsByAccount(accountId ?? 1, currentUserId, currentPage ?? 1);
                var transactionsViewModel = accountTransactions.Select(t => transactionMapper.MapFrom(t));
                var accountPreSelected = await accountService.GetAccountAsync((long)accountId);
                var accountViewModel = accountMapper.MapFrom(accountPreSelected);
                var count = await transactionService.GetTransactionsCount(currentUserId, accountId);
                var vm = new PaginationTransactionsViewModel()
                {
                    CurrentPage = currentPage ?? 1,
                    NextPage = (currentPage ?? 1) + 1,
                    PrevPage = (currentPage ?? 1) - 1,
                    Count = count,
                    Data = transactionsViewModel,
                    UserAccounts = accountsViewModels,
                    PreSelectedAccount = accountViewModel
                };

                return PartialView("Transactions/_AllUserTransactionsPartial", vm);
            }

        }


        [HttpPost]
        public async Task<IActionResult> SendTransaction(TransactionViewModel model)
        {

            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Index", "Dashboard", new { area = "User" });
                }
                var senderAccountNumber = string.Empty;
                if (model.SenderAccount == null)
                {
                    senderAccountNumber = model.SenderAccountID.ToString();
                }
                else
                {
                    senderAccountNumber = model.SenderAccount.AccountNumber;
                }
                var transaction = await transactionService.SendTransactionAsync(
                    senderAccountNumber,
                    model.ReceiverAccount.AccountNumber,
                    model.Description,
                    model.Amount);

                return Ok($"Transaction between {senderAccountNumber} and {model.ReceiverAccount.AccountNumber} was made successfully");
            }
            catch (ArgumentException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> SendSavedTransactions(long transactionId)
        {


            var transaction = await transactionService.SendSavedTransactionAsync(transactionId);


            return Ok($"Transaction between {transaction.SenderAccount.AccountNumber} " +
                $"and {transaction.ReceiverAccount.AccountNumber} was made successfully");

        }

        [HttpPost]
        public async Task<IActionResult> SaveTransaction(TransactionViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Index", "Dashboard", new { area = "User" });
                }
                var senderAccountNumber = string.Empty;
                if (model.SenderAccount == null)
                {
                    senderAccountNumber = model.SenderAccountID.ToString();
                }
                else
                {
                    senderAccountNumber = model.SenderAccount.AccountNumber;
                }
                var transaction = await transactionService.SaveTransactionAsync(
                    senderAccountNumber,
                    model.ReceiverAccount.AccountNumber,
                    model.Description,
                    model.Amount);

                return Ok($"Transaction between {senderAccountNumber} and {model.ReceiverAccount.AccountNumber} was made safed!");
            }
            catch (ArgumentException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpPost]
        public async Task<IActionResult> EditTransaction(TransactionViewModel model)
        {
            try

PaySharp.Web/Areas/User/Views/Transaction/List.cshtml
@model PaySharp.Web.ViewModels.PaginationTransactionsViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-12 col-lg-12">
    <div class="card-body">
        <span id="target-transaction-accounts">
            @await Html.PartialAsync("Transactions/_AllUserTransactionsPartial", Model)
        </span>
    </div>
</div>

@section Scripts
        {
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>

        $('#input-for-receiver-account').live('keyup.autocomplete', function () {
            console.log("auto");
            $(this).autocomplete({
                source: function (request, response) {
                    var dataToSend = $('#sender-account-selector option:selected').text();
                    $.ajax({
                        url: "/User/Account/FindSingleByAccName",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term, ignored: dataToSend },
                        success: function (data) {
                            allAccounts = data;
                            response($.map(data, function (item) {

                               
                                var itemToSave = Number(item.id);
                                $("#save-target-id").val(itemToSave);
                                var completeAccountListing = item.accountNumber;

                                return {
                                    label: completeAccountListing
                                };
                            }));

                        }
                    });
                },
                minLength: 3,
                delay: 500,
                minLength: 3,
                response: function (event, ui) {
                  
                    if (!ui.content.length) {
                        var noResult = { value: "", label: "No results found" };
                        ui.content.push(noResult);
                        $("#message-autocomplete").text("No results found");
                    } else {
                        $("#message-autocomplete").empty();

                    }
                }
            })
        });



    </script>
}

PaySharp.Web/Areas/User/Views/Transaction/MakePayment.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model PaySharp.Web.ViewModels.TransactionViewModel
@{
    ViewData["Title"] = "Makepayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-body col-lg-12">
    <form id="create-payment-form2" asp-controller="Transaction" asp-action="SendTransaction" method="post">
        <div class="card">
            <div class="page-heading">
                <div class="page-heading__container">
                    <h1 class="title">Transaction Template</h1>
                    <p class="caption">MAKE NEW PAYMENT</p>
                </div>
            </div>
            <div class="card-body">

                <div class="form-row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="auto" class="input-item-label">Sender Account</label>
                            <select class="form-control" asp-for="SenderAccountID" id="sender-account-selector">

                                <option disabled selected>Choose account</option>
                                @foreach (var account in Model.Accounts)
                                {
                            <option bal="@account.Balance" att="@account.ClientName" value="@account.AccountNumber">@account.AccountNumber - @account.ClientName
                                 - @account.NickName - @account.Balance</option>
                                }
                            </select>
                            <span asp-validation-for="SenderAccountID" class="text-danger"></span>
                            <div class="input-item input-with-label col-md-8" id="sender-client-name-div"></div>
                        </div>
              
                    </div>


                    <div class="col-6">

                        <div class="form-group">
                            <label for="auto" class="input-item-label">Receiver Account</label>
                            <input asp-for="ReceiverAccount.AccountNumber" id="input-for-receiver-account" class="form-control" type="text">
                            <span id="message-autocomplete" class="text-danger"></span>
                            <div class="input-item input-with-label col-md-8" id="receiver-client-name-div-2"></div>
                        </div>
                        <div id="receiver-client-name-div" class=""></div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-12">
                        <div class="form-group">
                            <label asp-for="Description">Description</label>
                            <input asp-for="Description" type="text" placeholder="Must be up to 35 characters" class="form-control">
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Amount">Amount</label>
                            <input asp-for="Amount" id="transaction-amount" type="text" placeholder="0.00" class="form-control">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <button type="submit" id="send-transaction" class="btn btn-success btn-block">Send</button>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label>&nbsp;</label>
                            <button type="submit" id="safe-transaction" class="btn btn-danger btn-block">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </form>

</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
                integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
                crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>

        $('#input-for-receiver-account').live('keyup.autocomplete', function () {
            console.log("auto");
            $(this).autocomplete({
                source: function (request, response) {
                    var dataToSend = $('#sender-account-selector option:selected').text();
                    $.ajax({
                        url: "/User/Account/FindSingleByAccName",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term, ignored: dataToSend },
                        success: function (data) {
                            allAccounts = data;
                            response($.map(data, function (item) {

                                var itemToSave = Number(item.id);
                                $("#save-target-id").val(itemToSave);
                                var completeAccountListing = item.accountNumber;
                                
                                return {
                                    label: completeAccountListing,
                                   
                                };
                            }));

                        }
                    });
                },
                minLength: 3,
                delay: 500,
                minLength: 3,
                select: function (event, ui) {
                    var clientName;

                    for (var i = 0; i < allAccounts.length; i++) {
                        if (allAccounts[i].accountNumber == ui.item.label) {
                            clientName = allAccounts[i].clientName
                        }
                    }
                 
                    $("#receiver-client-name-div-2").empty();
                     $("#receiver-client-name-div-2").text("Client Name: "+clientName);
             },
                response: function (event, ui) {
                    console.log("test");
                    
                    
                    if (!ui.content.length) {
                        var noResult = { value: "", label: "No results found" };
                        ui.content.push(noResult);
                        $("#receiver-client-name-div-2").text("No results found");
                    } else {
                        $("#receiver-client-name-div-2").empty();

                    }
                }
            })
        });

        </script>
}