PaySharp.Web/ViewModels/AccountViewModel.cs
using PaySharp.Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PaySharp.Web.ViewModels
{
    public class AccountViewModel
    {
        public long Id { get; set; }

        [StringLength(10, MinimumLength = 10)]
        public string AccountNumber { get; set; }

        [MinLength(3)]
        [MaxLength(35)]
        
        public string NickName { get; set; }

        [Required]
        [Range(0, Double.PositiveInfinity)]
        public decimal Balance { get; set; }

        public long UserId { get; set; }

        public bool IsAddedToUser { get; set; }

        public string ClientName { get; set; }
        public long ClientId { get; set; }
       // public Client Client { get; set; }
    }
}

PaySharp.Web/Areas/Administration/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PaySharp.Services.Contracts;
using PaySharp.Services.DTO;
using PaySharp.Services.Exceptions;
using PaySharp.Web.Mappers;
using PaySharp.Web.Utilities;
using PaySharp.Web.ViewModels;

namespace PaySharp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [CustomAuthorize("Admin")]
    public class AccountController : Controller
    {
        private readonly IAccountService accountService;
        private readonly IViewModelMapper<AccountDTO, AccountViewModel> accountMapper;

        public AccountController(IAccountService accountService,
            IViewModelMapper<AccountDTO, AccountViewModel> accountMapper)
        {
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string id)
        {
            try
            {
                var clientId = long.Parse(id);
                var account = await accountService.CreateAccountAsync(clientId);
               
                return Ok("Account created");
            }
            catch (EntityAlreadyExistsException ex)
            {

                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetUserAccounts(UserViewModel user)
        {
            var accounts = await accountService.GetUserClientsAccountsAsync(user.Id);
            var vm = accounts.Select(a => accountMapper.MapFrom(a)).ToList();
            for (int i = 0; i < vm.Count(); i++)
            {
                vm[i].UserId= user.Id;
            }
           
            return PartialView("Accounts/_AllClientAccountsPartial", vm);
        }

        [HttpGet]
        public async Task<IActionResult> GetClientAccounts(long id)
        {
            var accounts = await accountService.GetClientAccountsAsync(id);
            var vm = accounts.Select(a => accountMapper.MapFrom(a)).ToList();
            return PartialView("Accounts/_ShowClientAccountsPartial", vm);
        }

        
        [HttpGet]
        public async Task<IActionResult> AddAccountToUser(AccountViewModel account)
        {
            var res = await accountService.AddAccountToUserAsync(account.UserId, account.Id);
            return Ok("Account added to user");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveAccountFromUser(AccountViewModel account)
        {
            var res = await accountService.RemoveAccountFromUserAsync(account.UserId, account.Id);
            return Ok("Account removed from user");
        }
    }
}

PaySharp.Web/Areas/User/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PaySharp.Services.Contracts;
using PaySharp.Services.DTO;
using PaySharp.Web.Mappers;
using PaySharp.Web.Utilities;
using PaySharp.Web.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;


namespace PaySharp.Web.Areas.User.Controllers
{
    [Area("User")]
    [CustomAuthorize("User")]
    public class AccountController : Controller
    {
        private readonly IAuthorizationManager authorizationManager;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly IAccountService accountService;
        private readonly IViewModelMapper<AccountDTO, AccountViewModel> accountMapper;

        public AccountController(IAuthorizationManager authorizationManager,
            IHttpContextAccessor contextAccessor,
            IAccountService accountService,
            IViewModelMapper<AccountDTO, AccountViewModel> accountMapper)
        {
            this.authorizationManager = authorizationManager ?? throw new ArgumentNullException(nameof(authorizationManager));
            this.contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
        }
        [HttpPost]
        public async Task<IActionResult> Rename(long accountId, string newNickName)
        {
            var account = await accountService.RenameAccountAsync(accountId, newNickName);
            return Ok($"The account nickname was renamed to {newNickName}!");
        }

        [HttpGet]
        public async Task<IActionResult> GetUserAccounts()
        {
            var token = contextAccessor.HttpContext.Request.Cookies["SecurityToken"];
            var currentUserId = authorizationManager.GetLoggedUserId(token);
            var allUserAccounts = await accountService.GetUserAccountsAsync(currentUserId);
            var vm = allUserAccounts.Select(a => accountMapper.MapFrom(a)).ToList();

            return PartialView("Accounts/_AllUserAccountsPartial", vm);
        }
        [HttpGet]
        public async Task<IActionResult> GetAllUserAccounts()
        {
            var token = contextAccessor.HttpContext.Request.Cookies["SecurityToken"];
            var currentUserId = authorizationManager.GetLoggedUserId(token);
            var allUserAccounts = await accountService.GetUserAccountsAsync(currentUserId);
            var accounts = allUserAccounts.Select(a => accountMapper.MapFrom(a)).ToList();

            return Json(accounts);
        }


        [HttpPost]
        public async Task<JsonResult> FindSingleByAccName(string prefix)
        {

            if (string.IsNullOrEmpty(prefix))
            {
                return Json(string.Empty);
            }

            var allAccountsContaining = await accountService.FindAccountsContainingAsync(prefix);

            var allAccountsModels = allAccountsContaining.Select(a => accountMapper.MapFrom(a));

            return Json(allAccountsModels);

        }
    }
}

PaySharp.Web/Areas/User/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PaySharp.Services.Contracts;
using PaySharp.Services.DTO;
using PaySharp.Web.Mappers;
using PaySharp.Web.Utilities;
using PaySharp.Web.ViewModels;


namespace PaySharp.Web.Areas.User.Controllers
{
    [Area("User")]
    [CustomAuthorize("User")]
    public class DashboardController : Controller
    {
        private readonly IAuthorizationManager authorizationManager;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly IAccountService accountService;
        private readonly IViewModelMapper<AccountDTO, AccountViewModel> accountMapper;

        public DashboardController(IAuthorizationManager authorizationManager,
            IHttpContextAccessor contextAccessor,
            IAccountService accountService,
            IViewModelMapper<AccountDTO, AccountViewModel> accountMapper)
        {
            this.authorizationManager = authorizationManager ?? throw new ArgumentNullException(nameof(authorizationManager));
            this.contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
        }
        public async Task<IActionResult> Index()
        {
            
            var token = contextAccessor.HttpContext.Request.Cookies["SecurityToken"];
            var currentUserId = authorizationManager.GetLoggedUserId(token);
            var allUserAccounts = await accountService.GetUserAccountsAsync(currentUserId);
            var vm = allUserAccounts.Select(a => accountMapper.MapFrom(a)).ToList();
          
            return View(vm);
        }
       
    }
}

PaySharp.Web/Areas/Administration/Views/Shared/Accounts/_AllClientAccountsPartial.cshtml
@model IEnumerable<PaySharp.Web.ViewModels.AccountViewModel>

    <div class="table-responsive">
        @if (Model.Count() == 0)
        {
            <p>No accounts</p>
        }
        else
        {
            <table id="table-all-clients" class="table margin-bottom-0">
                <thead>
                    <tr>
                        <th width="200" scope="col">Account Number</th>
                        <th width="200" scope="col">Client Name</th>
                    </tr>
                </thead>

                @foreach (var account in Model)
                {
                    <tbody>
                        <tr>
                            <td>
                                <div class="user user--rounded user--bordered">
                                    <div class="user__name">
                                        <strong>@account.AccountNumber</strong>

                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="user user--rounded user--bordered">
                                    <div class="user__name">
                                        <strong>@account.ClientName</strong>

                                    </div>
                                </div>
                            </td>
                            <td>
                                @if (account.IsAddedToUser)
                                {
                                    <div class="form-group row">
                                        <div class="col-sm-10">
                                            <label class="switch">
                                                <input class="checkbox-test" type="checkbox" checked data-id="@account.Id" data-userId="@account.UserId">
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                    @*<a class="remove-account-user-id btn btn-lg text-danger "
                                       asp-area="Administration" asp-controller="Account" asp-action="RemoveAccountFromUser" asp-route-id="@account.Id" asp-route-userId="@account.UserId">
                                        <i class="btn btn-light btn-sm">Remove account</i>
                                    </a>*@

                                    @*<button type="button" class="remove-account-user-id btn btn-light btn-sm" data-url="/Administration/Account/RemoveAccountFromUser/@account.Id" data-userId="@account.UserId" >Remove ajax Accounts</button>*@
                                }
                                else
                                {
                                    <div class="form-group row">
                                        <div class="col-sm-10">
                                            <label class="switch">
                                                <input class="checkbox-test" type="checkbox"  data-id="@account.Id" data-userId="@account.UserId">
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                   
                                }
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
        }
    </div>

          

PaySharp.Web/Areas/Administration/Views/Shared/Accounts/_AllUserAccountsPartial.cshtml
@model IEnumerable<PaySharp.Web.ViewModels.AccountViewModel>

<div class="card margin-bottom-0">
    <div class="card-body">
        <h4>Accounts</h4>
        <p class="subtitle margin-bottom-20">All user accounts</p>
        <div class="table-responsive">
            @if (Model.Count() == 0)
            {
                <p>No accounts</p>
            }
            else
            {
                <table id="table-all-accounts" class="table margin-bottom-0">
                    <thead>
                        <tr>
                            <th width="200" scope="col">Account Number</th>
                            <th width="200" scope="col">Balance</th>
                        </tr>
                    </thead>

                    @foreach (var account in Model)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    <div class="user user--rounded user--bordered">
                                        <div class="user__name">
                                            <strong>@account.AccountNumber</strong>

                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="user user--rounded user--bordered">
                                        <div class="user__name">
                                            <strong>@account.Balance</strong>
                                        </div>
                                    </div>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    }
                </table>
            }
        </div>
    </div>
</div>

PaySharp.Web/Areas/Administration/Views/Shared/Accounts/_CreateAccountPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model PaySharp.Web.ViewModels.AccountViewModel

<form id="#create-account-form" asp-area="Administration" asp-controller="Account" asp-action="Create">
    <div class="form-group">
        <div asp-validation-summary="All" class="text-danger"></div>
        @*<label asp-for="NickName"></label>
        <input asp-for="NickName" type="text" class="form-control">
        <span asp-validation-for="NickName" class="form-text"></span>
        <a class="btn btn-lg text-danger "
           asp-area="Administration" asp-controller="Dashboard" asp-action="GenerateAccount">
            <i class="btn btn-light btn-sm">Generate Account Number</i>
        </a>*@

    </div>
    @*<div class="form-group margin-bottom-20">
        <label asp-for="AccountNumber"></label>
        <input asp-for="AccountNumber" type="text" class="form-control">
        <span asp-validation-for="AccountNumber" class="text-danger"></span>
    </div>*@
    @*<div class="form-group margin-bottom-20">
        <label asp-for="Balance"></label>
        <input asp-for="Balance" type="text" class="form-control">
        <span asp-validation-for="Balance" class="text-danger"></span>
    </div>*@
    <div class="form-group margin-bottom-20">
        <label asp-for="ClientId"></label>
        <input asp-for="ClientId" type="text" class="form-control">
        <span asp-validation-for="ClientId" class="text-danger"></span>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

</form>

PaySharp.Web/Areas/Administration/Views/Shared/Accounts/_ShowClientAccountsPartial.cshtml
@model IEnumerable<PaySharp.Web.ViewModels.AccountViewModel>

<div class="card margin-bottom-0">
    <div class="card-body">
        <h4>Accounts</h4>
        <p class="subtitle margin-bottom-20">All client accounts</p>
        <div class="table-responsive">
            @if (Model.Count() == 0)
            {
                <p>No accounts</p>
            }
            else
            {
                <table id="table-all-clients" class="table margin-bottom-0">
                    <thead>
                        <tr>
                            <th width="200" scope="col">Account Number</th>
                            <th width="200" scope="col">Balance</th>
                        </tr>
                    </thead>

                    @foreach (var account in Model)
                    {
                        <tbody>
                            <tr>
                                <td>
                                    <div class="user user--rounded user--bordered">
                                        <div class="user__name">
                                            <strong>@account.AccountNumber</strong>

                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="user user--rounded user--bordered">
                                        <div class="user__name">
                                            <strong>@account.Balance</strong>
                                        </div>
                                    </div>
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    }
                </table>
            }
        </div>
    </div>
</div>